-- CreateTable
CREATE TABLE `Issue` (
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `description` TEXT NOT NULL,
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `status` ENUM('CLOSED', 'IN_PROGRESS', 'OPEN') NOT NULL DEFAULT 'OPEN',
    `title` VARCHAR(255) NOT NULL,
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
