-- CreateTable
CREATE TABLE `Project` (
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `description` TEXT NOT NULL,
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `status` ENUM('CANCELLED', 'CONCEPTION', 'IN_PROGRESS', 'TERMINATED') NOT NULL DEFAULT 'CONCEPTION',
    `title` VARCHAR(255) NOT NULL,
    `updatedAt` DATETIME(3) NOT NULL,
    `assignedToUserId` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Project` ADD CONSTRAINT `Project_assignedToUserId_fkey` FOREIGN KEY (`assignedToUserId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
